# Generated by Django 3.2.6 on 2021-12-06 06:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20211203_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='apis.users')),
                ('password', models.CharField(default='password', max_length=20)),
                ('department', models.CharField(default='Dep1', max_length=20)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.AddField(
            model_name='record',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set(),
        ),
    ]
