version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build: ./backend
    volumes:
      - /static:app/backend/static
      - ./backend:/app/backend
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true
    command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  front:
    build: ./front
    volumes:
      - ./front:/app/frontend
      # One-way volume to use node_modules from inside image
      - /app/front/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    network_mode: host
    #ports:
    #  - '80:80'
    #  - '443:443'
    volumes:
      - /static:app/backend/static
    depends_on:
      - backend
      - front