# Generated by Django 3.2.6 on 2021-12-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='password', max_length=20),
        ),
        migrations.AlterField(
            model_name='diseasetype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
