# Generated by Django 3.2.6 on 2021-12-07 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20211206_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
